const {JSDOM}=require('jsdom');const fs=require('fs'),assert=require('assert');
const core=fs.readFileSync(__dirname+'/../edge/content.js','utf8');
const dom=new JSDOM('<!doctype html><body><div class="video-js"><video src="https://media.example/test.mp4"></video></div><div class="captions-right">第一句</div>',{url:'https://ylb.nwafu.edu.cn/TeachingCenterStudentWeb/index.html#/aiClassroom',runScripts:'outside-only'});
const w=dom.window,d=w.document,v=d.querySelector('video'),calls=[];let fail=false;
w.HTMLElement.prototype.getBoundingClientRect=()=>({left:20,top:20,width:800,height:450});Object.defineProperties(v,{readyState:{get:()=>4},currentSrc:{get:()=>v.src},paused:{get:()=>false}});
class Param{setTargetAtTime(x){this.value=x}}class Node{constructor(){this.frequency=new Param;this.gain=new Param;this.Q=new Param;this.threshold=new Param;this.knee=new Param;this.ratio=new Param;this.attack=new Param;this.release=new Param}connect(){}}
w.AudioContext=class{constructor(){this.destination=new Node;this.currentTime=0}resume(){return Promise.resolve()}close(){return Promise.resolve()}createMediaElementSource(){calls.push('source');return new Node}createBiquadFilter(){return new Node}createGain(){return new Node}createDynamicsCompressor(){return new Node}};
w.Audio=class extends w.EventTarget{constructor(){super();this.currentTime=0;this.volume=1}load(){if(this.src)setTimeout(()=>this.dispatchEvent(new w.Event(fail?'error':'canplay')),0)}play(){return Promise.resolve()}pause(){}removeAttribute(){this.src=''}};
const wait=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{try{w.eval(core);const sh=d.querySelector('#nwa-classroom-host').shadowRoot,$=x=>sh.getElementById(x);assert.equal($('caption').textContent,'第一句');d.querySelector('.captions-right').textContent='更新后的字幕';await wait(200);assert.equal($('caption').textContent,'更新后的字幕');$('size').value=42;$('size').dispatchEvent(new w.Event('input'));assert.equal($('caption').style.fontSize,'42px');assert.equal(JSON.parse(w.localStorage.getItem('nwa-classroom-enhancer-v1')).size,42);
$('fullscreen').click();await wait(0);assert(d.querySelector('.nwa-stage'));$('webfull').click();assert(!d.querySelector('.nwa-stage'));
const anchor=v.parentElement;anchor.requestFullscreen=()=>{d.fullscreenElement=anchor;d.dispatchEvent(new w.Event('fullscreenchange'));return Promise.resolve()};$('fullscreen').click();await wait(0);assert(anchor.contains(d.querySelector('#nwa-classroom-host')));d.fullscreenElement=null;d.dispatchEvent(new w.Event('fullscreenchange'));
$('audio').click();await wait(30);assert.equal($('audio').textContent,'恢复原声');assert.equal(v.muted,true);$('audio').click();assert.equal(v.muted,false);assert.equal($('audio').textContent,'启用音频增强');const before=calls.length;fail=true;$('audio').click();await wait(30);assert.equal(v.muted,false);assert.equal(calls.length,before);assert($('status').textContent.includes('原视频与原声保留'));await wait(220);assert($('status').textContent.includes('原视频与原声保留'));console.log('PASS DOM/mock media: subtitle polling, style persistence, fullscreen host, fallback, restore, CORS failure without audio interception, persistent error message.');}finally{w.close()}})().catch(e=>{console.error(e);process.exitCode=1});
