const {chromium}=require('playwright');const fs=require('fs');const http=require('http');const vm=require('vm');const assert=require('assert');
const base=__dirname+'/..';const source=fs.readFileSync(base+'/core.js','utf8').replace('__WORKLET_SOURCE__',JSON.stringify(fs.readFileSync(base+'/denoise-worklet.js','utf8')));
// Deterministic DSP: calibrated broadband noise must be attenuated; bypass preserves energy.
let Processor;vm.runInNewContext(fs.readFileSync(base+'/denoise-worklet.js','utf8'),{AudioWorkletProcessor:class{constructor(){this.port={postMessage(){}}}},sampleRate:48000,registerProcessor:(n,C)=>Processor=C,Float32Array,Float64Array,Math});
let seed=123;const noise=()=>{seed=(1664525*seed+1013904223)>>>0;return (seed/4294967296-.5)*.08};const p=new Processor();p.port.onmessage({data:{type:'calibrate'}});
for(let j=0;j<600;j++)p.process([[Float32Array.from({length:128},noise)]],[[new Float32Array(128)]]);
let x=0,y=0;for(let j=0;j<300;j++){const i=Float32Array.from({length:128},noise),o=new Float32Array(128);p.process([[i]],[[o]]);for(let k=0;k<128;k++){x+=i[k]**2;y+=o[k]**2}}
assert(y/x<.5,`noise attenuation ${y/x}`);console.log('DSP calibrated noise power ratio',+(y/x).toFixed(3));
const fixture=`<!doctype html><html><body style="margin:0;background:#222"><div class="video-js" style="width:800px;height:450px;background:#183346"><video style="width:100%;height:100%" controls src="/test.wav"></video></div><div class="video-captions"><div class="captions-right">这是第一句课堂字幕。</div></div></body></html>`;
const rate=48000,len=rate*12;const wav=Buffer.alloc(44+len*2);wav.write('RIFF');wav.writeUInt32LE(36+len*2,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(rate,24);wav.writeUInt32LE(rate*2,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(len*2,40);for(let i=0;i<len;i++)wav.writeInt16LE(Math.round(Math.sin(i/rate*2*Math.PI*440)*3000),44+i*2);
const server=http.createServer((req,res)=>{if(req.url==='/test.wav'){res.setHeader('Content-Type','audio/wav');res.end(wav)}else{res.setHeader('Content-Type','text/html');res.end(fixture)}});
(async()=>{await new Promise(r=>server.listen(8765,'127.0.0.1',r));const browser=await chromium.launch({headless:true,args:['--autoplay-policy=no-user-gesture-required']});try{const page=await browser.newPage({viewport:{width:1100,height:800}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8765');await page.addScriptTag({content:source});const h=page.locator('#nwa-classroom-host');await h.locator('#open').click();assert.equal(await h.locator('#caption').textContent(),'这是第一句课堂字幕。');await page.locator('.captions-right').evaluate(e=>e.textContent='第二句：字幕跟随倍速。');await page.waitForTimeout(250);assert.equal(await h.locator('#caption').textContent(),'第二句：字幕跟随倍速。');await h.locator('#size').fill('42');await h.locator('#size').dispatchEvent('input');assert.equal(await h.locator('#caption').evaluate(e=>getComputedStyle(e).fontSize),'42px');await h.locator('#fullscreen').click();await page.waitForTimeout(200);assert(await page.evaluate(()=>document.fullscreenElement?.contains(document.querySelector('#nwa-classroom-host'))));await page.evaluate(()=>document.exitFullscreen());await h.locator('#open').click();await page.locator('video').evaluate(v=>v.play());await h.locator('#audio').click();await page.waitForFunction(()=>document.querySelector('#nwa-classroom-host').shadowRoot.querySelector('#audio').textContent==='恢复原声');assert(await page.locator('video').evaluate(v=>v.muted));await h.locator('#noise').click();await page.waitForTimeout(1900);assert((await h.locator('#status').textContent()).includes('采样完成'));await h.locator('#audio').click();assert.equal(await page.locator('video').evaluate(v=>v.muted),false);await page.screenshot({path:base+'/preview.png'});assert.deepEqual(errors,[]);console.log('PASS: subtitle updates, style settings, fullscreen containment, audio start/calibration/restore; no page errors');
await page.reload();await page.addScriptTag({content:source});await h.locator('#open').click();assert.equal(await h.locator('#size').inputValue(),'42');console.log('PASS: saved preferences restored');
// Audio rejection keeps original audible: second server intentionally omits CORS.
const cross=http.createServer((req,res)=>{res.setHeader('Content-Type','audio/wav');res.end(wav)});await new Promise(r=>cross.listen(8766,'127.0.0.1',r));try{await page.locator('video').evaluate(v=>{v.src='http://127.0.0.1:8766/test.wav';v.load()});await page.waitForFunction(()=>document.querySelector('video').readyState>=2);await page.locator('video').evaluate(v=>v.play());await h.locator('#audio').click();await page.waitForFunction(()=>document.querySelector('#nwa-classroom-host').shadowRoot.querySelector('#status').textContent.includes('原视频与原声保留'));assert.equal(await page.locator('video').evaluate(v=>v.muted),false);console.log('PASS: CORS denial preserves original audio')}finally{cross.close()}
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
